import { MarkerType, Position } from "reactflow";
import styles from '../packages/ui/CircleNode/style.module.css';

// This nodes array contains the data corresponding to all nodes i.e. total is 16 nodes.
export const nodes = [
	{
	  id: 'staffA',
	  position: { x: 260, y: 90 },
	  data: {
		label: 'Finance/FP&A',
		tooltipcontent1: 'Senior Financial/FP&A Analyst',
		tooltipcontent2: 'Financial/FP&A Analyst',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffA-staffA',
			source: 'staffA',
			target: 'staffA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffA-mngmtA',
			source: 'staffA',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffB-staffA',
			source: 'staffB',
			target: 'staffA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },{
			id: 'staffE-staffA',
			source: 'staffE',
			target: 'staffA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: '#ef4444', fontSize: '0.8125rem' },
	},
	{
	  id: 'staffB',
	  position: { x: 260, y: 220 },
	  data: {
		label: 'Treasury',
		tooltipcontent1: 'Treasury Analyst',
		//tooltipcontent2: '',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffB->staffA',
			source: 'staffB',
			target: 'staffA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffB->mngmtB',
			source: 'staffB',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffB->staffE',
			source: 'staffB',
			target: 'staffE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: '#ef4444', fontSize: '0.8125rem' },
	},
	{
	  id: 'staffC',
	  position: { x: 260, y: 340 },
	  data: {
		label: 'Accounting',
		tooltipcontent1: 'Accountant',
		tooltipcontent2: 'Accounting Clerk',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffC->staffC',
			source: 'staffC',
			target: 'staffC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffC->mngmtC',
			source: 'staffC',
			target: 'mngmtC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: '#ef4444', fontSize: '0.8125rem' },
	},
	{
	  id: 'staffD',
	  position: { x: 260, y: 460 },
	  data: {
		label: 'Audit',
		tooltipcontent1: 'Auditor',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffD->mngmtD',
			source: 'staffD',
			target: 'mngmtD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: '#ef4444', fontSize: '0.8125rem' },
	},
	{
	  id: 'staffE',
	  position: { x: 260, y: 580 },
	  data: {
		label: 'Tax',
		tooltipcontent1: 'Tax Accountant',
		tooltipcontent2: 'Tax Analyst',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffE->staffE',
			source: 'staffE',
			target: 'staffE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffE->staffA',
			source: 'staffE',
			target: 'staffA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffE->mngmtE',
			source: 'staffE',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffB->staffE',
			source: 'staffB',
			target: 'staffE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: '#ef4444', fontSize: '0.8125rem' },
	},
	// management starts
	{
	  id: 'mngmtA',
	  position: { x: 650, y: 90 },
	  data: {
		label: 'Finance/FP&A',
		tooltipcontent1: 'Director, Finance/FP&A',
		tooltipcontent2: 'Manager, Finance/FP&A ',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffA->mngmtA',
			source: 'staffA',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->mngmtA',
			source: 'mngmtA',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->extveB',
			source: 'mngmtA',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->mngmtE',
			source: 'mngmtA',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->mngmtB',
			source: 'mngmtA',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->mngmtA',
			source: 'mngmtB',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtA',
			source: 'mngmtC',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mngmtA',
			source: 'mngmtD',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(250, 164, 43)', fontSize: '0.8125rem' },
	},
	{
	  id: 'mngmtB',
	  position: { x: 650, y: 220 },
	  data: {
		label: 'Treasury',
		tooltipcontent1: 'Director, Treasury ',
		tooltipcontent2: 'Director, Risk Management',
		tooltipcontent3: 'Manager, Treasury',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffB->mngmtB',
			source: 'staffB',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->extveC',
			source: 'mngmtB',
			target: 'extveC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->mngmtB',
			source: 'mngmtB',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->mgmntA',
			source: 'mngmtB',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->mgmntB',
			source: 'mngmtA',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->mgmntE',
			source: 'mngmtB',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mgmntB',
			source: 'mngmtC',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mgmntB',
			source: 'mngmtD',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(250, 164, 43)', fontSize: '0.8125rem' },
	},
	{
	  id: 'mngmtC',
	  position: { x: 650, y: 340 },
	  data: {
		label: 'Accounting',
		tooltipcontent1: 'Director, Accounting',
		tooltipcontent2: 'Manager, Accounting',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'staffC->mngmtC',
			source: 'staffC',
			target: 'mngmtC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->extveD',
			source: 'mngmtC',
			target: 'extveD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtC',
			source: 'mngmtC',
			target: 'mngmtC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtA',
			source: 'mngmtC',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtB',
			source: 'mngmtC',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtD',
			source: 'mngmtC',
			target: 'mngmtD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtE',
			source: 'mngmtC',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(250, 164, 43)', fontSize: '0.8125rem' },
	},
	{
	  id: 'mngmtD',
	  position: { x:650, y: 460 },
	  data: {
		label: 'Audit',
		tooltipcontent1: 'Director, Audit',
		tooltipcontent2: 'Manager, Audit',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'mngmtD->mngmtD',
			source: 'mngmtD',
			target: 'mngmtD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffD->mngmtD',
			source: 'staffD',
			target: 'mngmtD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->extveE',
			source: 'mngmtD',
			target: 'extveE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mngmtE',
			source: 'mngmtD',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mngmtA',
			source: 'mngmtD',
			target: 'mngmtA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mngmtB',
			source: 'mngmtD',
			target: 'mngmtB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtD',
			source: 'mngmtC',
			target: 'mngmtD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(250, 164, 43)', fontSize: '0.8125rem' },
	},
	{
	  id: 'mngmtE',
	  position: { x: 650, y: 580 },
	  data: {
		label: 'Tax',
		tooltipcontent1: 'Director, Tax',
		tooltipcontent2: 'Manager, Tax',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'mngmtE->mngmtE',
			source: 'mngmtE',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtE->extveF',
			source: 'mngmtE',
			target: 'extveF',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'staffE->mngmtE',
			source: 'staffE',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->mngmtE',
			source: 'mngmtA',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtB->mngmtE',
			source: 'mngmtB',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtC->mngmtE',
			source: 'mngmtC',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtD->mngmtE',
			source: 'mngmtD',
			target: 'mngmtE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(250, 164, 43)', fontSize: '0.8125rem' },
	},
	// executive starts
	{
	  id: 'extveA',
	  position: { x: 1040, y: 90 },
	  data: {
		label: 'Chief Financial Officer',
		//tooltipcontent1: 'Chief Financial Officer',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'extveB->extveA',
			source: 'extveB',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveA',
			source: 'extveC',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveD->extveA',
			source: 'extveD',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
	{
	  id: 'extveB',
	  position: { x: 1040, y: 180 },
	  data: {
	    label: 'Vice President, Finance/FP&A',
		tooltipcontent1: 'Vice President, Finance/FP&A',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'extveB->extveA',
			source: 'extveB',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'mngmtA->extveB',
			source: 'mngmtA',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveB',
			source: 'extveC',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveD->extveB',
			source: 'extveD',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
	{
	  id: 'extveC',
	  position: { x: 1040, y: 280 },
	  data: {
		label: 'Treasurer',
		tooltipcontent1: 'Treasurer',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'mngmtB->extveC',
			source: 'mngmtB',
			target: 'extveC',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveA',
			source: 'extveC',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveB',
			source: 'extveC',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveD2',
			source: 'extveC',
			target: 'extveD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
	{
	  id: 'extveD',
	  position: { x: 1040, y: 380 },
	  data: {
		label: 'Controller',
		tooltipcontent1: 'Controller',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'mngmtC->extveD',
			source: 'mngmtC',
			target: 'extveD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveD->extveA',
			source: 'extveD',
			target: 'extveA',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveD->extveB',
			source: 'extveD',
			target: 'extveB',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		  {
			id: 'extveC->extveD',
			source: 'extveC',
			target: 'extveD',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
	{
	  id: 'extveE',
	  position: { x: 1040, y: 480 },
	  data: {
	   label: 'Vice President, Audit',
		tooltipcontent1: 'Vice President, Audit',
		toolbarPosition: Position.Right,
		link: [
		  ,
		  {
			id: 'mngmtD->extveE',
			source: 'mngmtD',
			target: 'extveE',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
	{
	  id: 'extveF',
	  position: { x: 1040, y: 580 },
	  data: {
		label: 'Vice President, Tax',
		tooltipcontent1: 'Vice President, Tax',
		toolbarPosition: Position.Right,
		link: [
		  {
			id: 'mngmtE->extveF',
			source: 'mngmtE',
			target: 'extveF',
			markerEnd: {
			  type: MarkerType.ArrowClosed,
			  width: 40,
			  height: 40,
			  color: 'white',
			},
		  },
		],
	  },
	  draggable: false,
	  className: styles.circle,
	  style: { background: 'rgb(125, 208, 225)', fontSize: '0.8125rem' },
	},
  ]